#? Config file for btop v. 1.4.7

color_theme = "novalab"
theme_background = False
truecolor = True
force_tty = False

vim_keys = True
disable_mouse = False
rounded_corners = True
terminal_sync = True

graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"

shown_boxes = "cpu mem net proc"
update_ms = 2000

proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
proc_info_smaps = False
proc_left = False
proc_filter_kernel = True
proc_follow_detailed = True
proc_aggregate = False

cpu_graph_upper = "Auto"
cpu_graph_lower = "Auto"
cpu_invert_lower = True
cpu_single_graph = False
cpu_bottom = False

show_uptime = True
show_cpu_watts = False
check_temp = True
cpu_sensor = "Auto"
show_coretemp = False
temp_scale = "celsius"
show_cpu_freq = True

clock_format = "/host | %H:%M:%S"
background_update = True

base_10_sizes = False
mem_graphs = True
mem_below_net = False
zfs_arc_cached = True

show_swap = True
swap_disk = False
show_disks = True
only_physical = True
use_fstab = False
zfs_hide_datasets = False
disk_free_priv = False
show_io_stat = True
io_mode = False
io_graph_combined = False

net_download = 100
net_upload = 100
net_auto = True
net_sync = True
net_iface = ""
base_10_bitrate = "Auto"

show_battery = False
show_battery_watts = False
selected_battery = "Auto"

log_level = "WARNING"
save_config_on_exit = True
